CREATE DATABASE IF NOT EXISTS blog
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENCRYPTION='N';

USE blog;

CREATE TABLE IF NOT EXISTS entries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO entries (title, content) VALUES ('Hello, 世界', 'Welcome!');
